export const API_PATHS = {
  LOG_IN: "/auth/login",
  FORGOT_PASSWORD: "/users/password/forgot",
  USERS: "/users",
  USERS_EMAIL: "/users/email",
  USERS_LANG: "/users/lang",
  USERS_UPDATE: "/users/update",
  COMPANIES: "/companies",
  COMPANIES_TOKEN_REFRESH: "/companies/token/refresh",
  CONTROLLERS: "/controllers",
  CONTROLLERS_UPDATE: "/controllers/update",
  GET_CONTROLLER: (id: string) => `/controllers/${id}`,
  BULK_UPLOAD_TEMPLATE: "/bulk-upload/template",
  BULK_UPLOAD_IMPORT: "/bulk-upload/import",
  METERS: "/meters",
  GET_METER: (id: string) => `/meters/${id}`,
  GET_READINGS: (meterId: string) => `/readings/${meterId}`,
};
