export const metersKeys = {
  all: ["meters"] as const,
  list: (
    page: number,
    limit: number,
    search: string,
    isArchived: boolean,
    companyId: string,
    locationType: string,
    meterStatus: string,
    accountNumber: string,
    clientName: string,
    address: string,
    isValveLockedByManager: string,
  ) =>
    [
      ...metersKeys.all,
      page,
      limit,
      search,
      isArchived,
      companyId,
      locationType,
      meterStatus,
      accountNumber,
      clientName,
      address,
      isValveLockedByManager,
    ] as const,
  details: (id: string) => [...metersKeys.all, "details", id] as const,
};
